name: flutter_native_video_pageview
publish_to: 'none'
description: PageView with native video players (Android ExoPlayer / iOS AVPlayer) controlled from main page.
version: 1.0.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true